spring.application.name=springvehiclelog

spring.datasource.url=jdbc:mysql://91.98.141.19/vehiclelog
spring.datasource.username=root
spring.datasource.password=lF9cstcJGwwNvEYqVpfRRdhvrtjYRI1XMaSsyEuTwTMqeI83Rsy0yVzcwvfCwUYf
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.level.org.springframework.web=DEBUG